log:
  level: debug
  disable_sentry: true

db:
  url: "postgres://book:book@localhost:21999/book?sslmode=disable"

mime_types:
  banner:
    - image/png
    - image/jpeg
    - image/jpg
  file:
    - application/pdf

listener:
  addr: :8732

update_tracker:
  name: update_tracker # Name to be displayed in logs
  capacity: 1
  iteration_size: 10000
  runner: # Periods settings
    normal_period: 10s
    min_abnormal_period: 10s
    max_abnormal_period: 10s

ethereum_client: # Rpc and WS addresses
  rpc: https://eth-goerli.g.alchemy.com/v2/DTb8jEsvO6jtXEwUM9Ri3k3cufBIJX-R
  web_socket: wss://eth-goerli.g.alchemy.com/v2/DTb8jEsvO6jtXEwUM9Ri3k3cufBIJX-R

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: book-svc
  service_port: 80

doorman:
  service_url: http://localhost:8054/integrations/doorman

