log:
  level: debug
  disable_sentry: true

db:
  url: "postgres://book:book@localhost:21999/book?sslmode=disable"

mime_types:
  banner:
    - image/png
    - image/jpeg
    - image/jpg
  file:
    - application/pdf

connector:
  url:
  token:

listener:
  addr: :8732

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: book-svc
  service_port: 80


